In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score

import pandas as pd
import numpy as np

In [4]:
cancer_data = load_breast_cancer()

In [5]:
df = pd.DataFrame(data=cancer_data.data, columns=cancer_data.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [6]:
cancer_data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [7]:
cancer_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
df['target'] = cancer_data.target

In [9]:
df.target.value_counts()

1    357
0    212
Name: target, dtype: int64

In [10]:
lr = LogisticRegression()

In [11]:
trainX,testX,trainY,testY = train_test_split(cancer_data.data, cancer_data.target)

In [ ]:
lr.fit(trainX,trainY)

In [13]:
lr.coef_

array([[ 1.92815758e+00,  2.13074538e-01, -1.15102003e-01,
         1.52496777e-04, -8.12940852e-02, -3.65928734e-01,
        -5.05247622e-01, -2.06508014e-01, -1.19032970e-01,
        -2.52075001e-02,  7.93950122e-02,  1.13003402e+00,
         3.33962915e-01, -1.13994953e-01, -7.58094825e-03,
        -7.94438314e-02, -1.08238658e-01, -2.69434175e-02,
        -3.34150639e-02, -7.62561226e-03,  1.99897424e+00,
        -4.03294190e-01, -1.73663553e-01, -2.66187901e-02,
        -1.46595021e-01, -1.15420823e+00, -1.37408648e+00,
        -3.92722957e-01, -3.98028355e-01, -1.16589292e-01]])

In [25]:
lr.intercept_

array([0.23928864])

In [24]:
pd.DataFrame({'features':cancer_data.feature_names, 'weights': lr.coef_.flatten()})

features   weights
0               mean radius  1.195204
1              mean texture  0.408101
2            mean perimeter  0.427945
3                 mean area -0.024553
4           mean smoothness -0.041764
5          mean compactness -0.202502
6            mean concavity -0.285056
7       mean concave points -0.115887
8             mean symmetry -0.054523
9    mean fractal dimension -0.010852
10             radius error  0.055675
11            texture error  0.477318
12          perimeter error  0.238244
13               area error -0.142548
14         smoothness error -0.003106
15        compactness error -0.048456
16          concavity error -0.063394
17     concave points error -0.015484
18           symmetry error -0.012475
19  fractal dimension error -0.004959
20             worst radius  1.296627
21            worst texture -0.523142
22          worst perimeter -0.422636
23               worst area -0.009020
24         worst smoothness -0.073037
25        worst compactness -0.644268
26          worst concavity -0.792735
27     worst concave points -0.226053
28           worst symmetry -0.174987
29  worst fractal dimension -0.064281

In [11]:
pred = lr.predict(testX)

In [28]:
pd.DataFrame({'target':testY,'pred':pred})

target  pred
0         1     1
1         1     1
2         1     1
3         1     1
4         0     0
..      ...   ...
138       0     0
139       0     0
140       1     1
141       1     1
142       1     1

[143 rows x 2 columns]

In [31]:
pred_sigmoid = lr.predict_proba(testX)[:,1]
pd.DataFrame({'target':testY,'pred':pred_sigmoid})

target      pred
0         1  0.999821
1         1  0.962946
2         1  0.998955
3         1  0.996431
4         0  0.001079
..      ...       ...
138       0  0.008639
139       0  0.000016
140       1  0.999288
141       1  0.907092
142       1  0.978288

[143 rows x 2 columns]

In [32]:
accuracy_score(y_pred=pred,y_true=testY)

0.9440559440559441

In [33]:
confusion_matrix(y_pred=pred,y_true=testY)

array([[47,  3],
       [ 5, 88]])

In [15]:
import numpy as np
def sigmoid(x):
    return 1.0/(1+np.exp(-x))

In [16]:
sigmoid(0.5)

0.6224593312018546

In [14]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

In [15]:
softmax(np.array([-0.3,-0.4]))

array([0.52497919, 0.47502081])